insert into Theatre (tname, address, zip) values ('Cardify', '83 Everett Pass', '2');
insert into Theatre (tname, address, zip) values ('Fixflex', '6632 Rowland Center', '39');
insert into Theatre (tname, address, zip) values ('Ronstring', '0 Beilfuss Avenue', '77');
insert into Theatre (tname, address, zip) values ('Bytecard', '56 Mcbride Pass', '49');
insert into Theatre (tname, address, zip) values ('It', '58 Hansons Drive', '940');
insert into Theatre (tname, address, zip) values ('Ronstring', '7 Dexter Way', '64198');
insert into Theatre (tname, address, zip) values ('Lotlux', '5232 South Drive', '158');
insert into Theatre (tname, address, zip) values ('Namfix', '6 Harbort Trail', '43051');
insert into Theatre (tname, address, zip) values ('Mat Lam Tam', '158 Pepper Wood Avenue', '2645');
insert into Theatre (tname, address, zip) values ('Veribet', '44234 Sunfield Center', '238');
insert into Theatre (tname, address, zip) values ('Tempsoft', '13 Crest Line Alley', '94');
insert into Theatre (tname, address, zip) values ('Fix San', '86 Cottonwood Alley', '623');
insert into Theatre (tname, address, zip) values ('Fixflex', '6 Nancy Circle', '51');
insert into Theatre (tname, address, zip) values ('Lotstring', '5786 Namekagon Crossing', '459');
insert into Theatre (tname, address, zip) values ('Konklab', '09494 Lotheville Street', '2');
insert into Theatre (tname, address, zip) values ('Wrapsafe', '76528 Rutledge Circle', '0');
insert into Theatre (tname, address, zip) values ('Rank', '03 Pond Road', '06773');
insert into Theatre (tname, address, zip) values ('Span', '417 Chinook Plaza', '24624');
insert into Theatre (tname, address, zip) values ('Y-Solowarm', '04780 Superior Junction', '5');
insert into Theatre (tname, address, zip) values ('Viva', '77213 Sutteridge Pass', '5');
insert into Theatre (tname, address, zip) values ('Job', '271 Muir Point', '8639');
insert into Theatre (tname, address, zip) values ('Cardify', '8 Northfield Circle', '02850');
insert into Theatre (tname, address, zip) values ('Temp', '699 Del Mar Junction', '990');
insert into Theatre (tname, address, zip) values ('Andalax', '85823 Kennedy Hill', '941');
insert into Theatre (tname, address, zip) values ('Biodex', '7 Columbus Crossing', '303');
insert into Theatre (tname, address, zip) values ('Bitwolf', '339 Donald Trail', '6');
insert into Theatre (tname, address, zip) values ('Domainer', '030 Rusk Parkway', '3');
insert into Theatre (tname, address, zip) values ('Treeflex', '17257 Holmberg Junction', '78');
insert into Theatre (tname, address, zip) values ('Biodex', '34 David Point', '8790');
insert into Theatre (tname, address, zip) values ('Bitchip', '308 Mallard Drive', '6');
insert into Theatre (tname, address, zip) values ('Treeflex', '5656 Ludington Court', '234');
insert into Theatre (tname, address, zip) values ('Lotlux', '0017 Independence Parkway', '1');
insert into Theatre (tname, address, zip) values ('Duobam', '55432 Hollow Ridge Parkway', '40353');
insert into Theatre (tname, address, zip) values ('Sub-Ex', '52007 Morning Road', '34');
insert into Theatre (tname, address, zip) values ('Trippledex', '21 Shopko Point', '9');
insert into Theatre (tname, address, zip) values ('Vagram', '887 Cottonwood Crossing', '261');
insert into Theatre (tname, address, zip) values ('Cardguard', '869 Kennedy Way', '620');
insert into Theatre (tname, address, zip) values ('Stringtough', '72 Green Ridge Drive', '672');
insert into Theatre (tname, address, zip) values ('Alpha', '598 Warner Terrace', '3');
insert into Theatre (tname, address, zip) values ('Kanlam', '7 Fallview Hill', '81');
insert into Theatre (tname, address, zip) values ('Stringtough', '933 Ridgeview Circle', '1');
insert into Theatre (tname, address, zip) values ('Stim', '20 Menomonie Point', '740');
insert into Theatre (tname, address, zip) values ('Temp', '15813 Iowa Park', '6779');
insert into Theatre (tname, address, zip) values ('Bigtax', '02069 Sundown Drive', '21776');
insert into Theatre (tname, address, zip) values ('Viva', '55 Hovde Plaza', '352');
insert into Theatre (tname, address, zip) values ('Alpha', '88 Bartillon Circle', '44');
insert into Theatre (tname, address, zip) values ('Span', '218 Marquette Plaza', '1');
insert into Theatre (tname, address, zip) values ('Cookley', '639 Pepper Wood Plaza', '73112');
insert into Theatre (tname, address, zip) values ('Cardguard', '53222 Loeprich Crossing', '09326');
insert into Theatre (tname, address, zip) values ('Stringtough', '3 Weeping Birch Alley', '1446');
insert into Theatre (tname, address, zip) values ('Hatity', '3940 Summer Ridge Parkway', '874');
insert into Theatre (tname, address, zip) values ('Biodex', '5619 Oxford Road', '6');
insert into Theatre (tname, address, zip) values ('Redhold', '5 Doe Crossing Point', '1027');
insert into Theatre (tname, address, zip) values ('Bitwolf', '58 Independence Hill', '770');
insert into Theatre (tname, address, zip) values ('Zathin', '1112 Kenwood Parkway', '598');
insert into Theatre (tname, address, zip) values ('Opela', '061 Oak Point', '85');
insert into Theatre (tname, address, zip) values ('Transcof', '58490 Golf Course Road', '3');
insert into Theatre (tname, address, zip) values ('Flowdesk', '48374 Becker Court', '2');
insert into Theatre (tname, address, zip) values ('Sub-Ex', '6266 Eagan Avenue', '5526');
insert into Theatre (tname, address, zip) values ('Sonsing', '488 Vernon Trail', '51');
insert into Theatre (tname, address, zip) values ('Sonair', '8996 Hayes Street', '9580');
insert into Theatre (tname, address, zip) values ('Stim', '73 Kim Point', '43897');
insert into Theatre (tname, address, zip) values ('Sonair', '062 Sunfield Street', '044');
insert into Theatre (tname, address, zip) values ('Konklux', '3385 Golf Course Plaza', '14470');
insert into Theatre (tname, address, zip) values ('Rank', '977 Reindahl Plaza', '4');
insert into Theatre (tname, address, zip) values ('Duobam', '9 Stoughton Way', '257');
insert into Theatre (tname, address, zip) values ('Stringtough', '574 Sycamore Alley', '738');
insert into Theatre (tname, address, zip) values ('Transcof', '4 Ryan Court', '052');
insert into Theatre (tname, address, zip) values ('Veribet', '89 Forest Run Terrace', '60224');
insert into Theatre (tname, address, zip) values ('Pannier', '72 Cody Lane', '7688');
insert into Theatre (tname, address, zip) values ('Subin', '031 Algoma Court', '81');
insert into Theatre (tname, address, zip) values ('Kanlam', '8630 Service Terrace', '84');
insert into Theatre (tname, address, zip) values ('Alphazap', '040 Barby Road', '5085');
insert into Theatre (tname, address, zip) values ('Fintone', '8407 Mayfield Hill', '5');
insert into Theatre (tname, address, zip) values ('Opela', '1 Vernon Lane', '840');
insert into Theatre (tname, address, zip) values ('Viva', '1 Southridge Park', '7');
insert into Theatre (tname, address, zip) values ('Aerified', '777 Shoshone Hill', '28');
insert into Theatre (tname, address, zip) values ('Bigtax', '491 Forest Place', '4560');
insert into Theatre (tname, address, zip) values ('Job', '932 Vera Court', '4');
insert into Theatre (tname, address, zip) values ('Opela', '2 4th Lane', '759');
insert into Theatre (tname, address, zip) values ('Transcof', '42 Twin Pines Way', '9711');
insert into Theatre (tname, address, zip) values ('Konklux', '520 Morrow Way', '9');
insert into Theatre (tname, address, zip) values ('Bitchip', '95198 Eliot Circle', '7395');
insert into Theatre (tname, address, zip) values ('Fix San', '7 Kim Pass', '1');
insert into Theatre (tname, address, zip) values ('Lotlux', '2302 Meadow Valley Road', '7');
insert into Theatre (tname, address, zip) values ('Span', '26609 Kennedy Place', '8382');
insert into Theatre (tname, address, zip) values ('Fintone', '066 High Crossing Drive', '45');
insert into Theatre (tname, address, zip) values ('Fixflex', '85 Wayridge Pass', '653');
insert into Theatre (tname, address, zip) values ('Redhold', '56 Moose Junction', '2');
insert into Theatre (tname, address, zip) values ('Namfix', '80 7th Junction', '8');
insert into Theatre (tname, address, zip) values ('Span', '2724 Loomis Parkway', '95041');
insert into Theatre (tname, address, zip) values ('Voltsillam', '4889 Parkside Street', '259');
insert into Theatre (tname, address, zip) values ('Vagram', '3905 Summer Ridge Way', '5987');
insert into Theatre (tname, address, zip) values ('Domainer', '3761 Delaware Court', '91');
insert into Theatre (tname, address, zip) values ('Ronstring', '8 Fremont Alley', '18');
insert into Theatre (tname, address, zip) values ('Viva', '99379 Golf Point', '6');
insert into Theatre (tname, address, zip) values ('Andalax', '8519 Thompson Circle', '8');
insert into Theatre (tname, address, zip) values ('Fixflex', '280 Acker Point', '7013');
insert into Theatre (tname, address, zip) values ('Fintone', '3 Dovetail Lane', '5');
insert into Theatre (tname, address, zip) values ('Rank', '171 Granby Park', '58');
insert into Theatre (tname, address, zip) values ('Subin', '5 Goodland Trail', '99');
insert into Theatre (tname, address, zip) values ('It', '87929 Prairie Rose Point', '53272');
insert into Theatre (tname, address, zip) values ('Ventosanzap', '70 Ohio Junction', '7988');
insert into Theatre (tname, address, zip) values ('Tresom', '330 Vernon Circle', '5019');
insert into Theatre (tname, address, zip) values ('Tin', '93887 Glacier Hill Road', '892');
insert into Theatre (tname, address, zip) values ('Fintone', '9 Kinsman Point', '53666');
insert into Theatre (tname, address, zip) values ('Andalax', '2058 Farragut Trail', '4097');
insert into Theatre (tname, address, zip) values ('Zaam-Dox', '72 Golf Terrace', '671');
insert into Theatre (tname, address, zip) values ('Daltfresh', '04 American Ash Junction', '1480');
insert into Theatre (tname, address, zip) values ('Latlux', '7436 Oxford Hill', '6');
insert into Theatre (tname, address, zip) values ('Bigtax', '3023 Steensland Circle', '28');
insert into Theatre (tname, address, zip) values ('Lotlux', '3195 Barby Alley', '6');
insert into Theatre (tname, address, zip) values ('Cardguard', '10 La Follette Place', '21');
insert into Theatre (tname, address, zip) values ('Trippledex', '523 Talisman Plaza', '8714');
insert into Theatre (tname, address, zip) values ('Tampflex', '9 Loomis Crossing', '19171');
insert into Theatre (tname, address, zip) values ('Y-Solowarm', '40 Buhler Lane', '80530');
insert into Theatre (tname, address, zip) values ('Bamity', '22837 Vidon Way', '7149');
insert into Theatre (tname, address, zip) values ('Cookley', '8 Crowley Place', '82');
insert into Theatre (tname, address, zip) values ('It', '5855 Pawling Lane', '65');
insert into Theatre (tname, address, zip) values ('Bamity', '8655 Meadow Ridge Center', '40368');
insert into Theatre (tname, address, zip) values ('Kanlam', '259 Cottonwood Hill', '04');
insert into Theatre (tname, address, zip) values ('Tres-Zap', '66643 Rusk Hill', '0631');
insert into Theatre (tname, address, zip) values ('Tin', '71 Lerdahl Lane', '20');
insert into Theatre (tname, address, zip) values ('Toughjoyfax', '836 Loomis Circle', '4353');
insert into Theatre (tname, address, zip) values ('Cookley', '5620 Bobwhite Way', '5549');
insert into Theatre (tname, address, zip) values ('Fix San', '24375 Blaine Hill', '6502');
insert into Theatre (tname, address, zip) values ('Wrapsafe', '58201 Dahle Center', '968');
insert into Theatre (tname, address, zip) values ('Keylex', '820 Del Sol Circle', '584');
insert into Theatre (tname, address, zip) values ('Stim', '0818 Hudson Way', '62');
insert into Theatre (tname, address, zip) values ('Biodex', '13677 Twin Pines Court', '602');
insert into Theatre (tname, address, zip) values ('Mat Lam Tam', '1 Summerview Park', '7842');
insert into Theatre (tname, address, zip) values ('Sub-Ex', '2513 Del Mar Plaza', '4');
insert into Theatre (tname, address, zip) values ('Tres-Zap', '93978 Eagan Terrace', '109');
insert into Theatre (tname, address, zip) values ('Treeflex', '5 7th Point', '48936');
insert into Theatre (tname, address, zip) values ('Biodex', '5 Corry Plaza', '9');
insert into Theatre (tname, address, zip) values ('Tres-Zap', '14 Straubel Avenue', '96');
insert into Theatre (tname, address, zip) values ('Stronghold', '7 Emmet Trail', '9');
insert into Theatre (tname, address, zip) values ('Temp', '5027 Declaration Lane', '4402');
insert into Theatre (tname, address, zip) values ('Tres-Zap', '9 Hudson Drive', '5');
insert into Theatre (tname, address, zip) values ('Holdlamis', '816 Carpenter Terrace', '8');
insert into Theatre (tname, address, zip) values ('Zathin', '029 Crescent Oaks Terrace', '673');
insert into Theatre (tname, address, zip) values ('Sonsing', '235 Continental Point', '62');
insert into Theatre (tname, address, zip) values ('Span', '89 Twin Pines Terrace', '559');
insert into Theatre (tname, address, zip) values ('Zoolab', '9 Meadow Ridge Point', '9008');
insert into Theatre (tname, address, zip) values ('Stronghold', '07 Stephen Drive', '92');
insert into Theatre (tname, address, zip) values ('Cookley', '7104 Dixon Place', '455');
insert into Theatre (tname, address, zip) values ('Fintone', '94 Mesta Court', '8');
insert into Theatre (tname, address, zip) values ('Span', '53921 Longview Drive', '745');
insert into Theatre (tname, address, zip) values ('Konklab', '79601 Ridgeview Junction', '5132');
insert into Theatre (tname, address, zip) values ('Veribet', '2 Lillian Street', '960');
insert into Theatre (tname, address, zip) values ('Keylex', '65 Beilfuss Crossing', '4236');
insert into Theatre (tname, address, zip) values ('Ronstring', '95635 Havey Circle', '48');
insert into Theatre (tname, address, zip) values ('Ronstring', '588 Prairie Rose Pass', '8');
insert into Theatre (tname, address, zip) values ('Sub-Ex', '5920 Kenwood Junction', '3209');
insert into Theatre (tname, address, zip) values ('Solarbreeze', '180 Becker Circle', '0');
insert into Theatre (tname, address, zip) values ('Bigtax', '867 Arrowood Park', '4146');
insert into Theatre (tname, address, zip) values ('Y-find', '164 Londonderry Center', '10');
insert into Theatre (tname, address, zip) values ('Home Ing', '79 Randy Lane', '47560');
insert into Theatre (tname, address, zip) values ('Rank', '40932 Dapin Alley', '68565');
insert into Theatre (tname, address, zip) values ('Lotstring', '653 Comanche Center', '1338');
insert into Theatre (tname, address, zip) values ('Wrapsafe', '88453 Miller Center', '66120');
insert into Theatre (tname, address, zip) values ('Bytecard', '2066 Evergreen Trail', '25');
insert into Theatre (tname, address, zip) values ('Veribet', '49513 Delaware Pass', '530');
insert into Theatre (tname, address, zip) values ('It', '2735 Eliot Way', '11');
insert into Theatre (tname, address, zip) values ('Namfix', '93 Mccormick Place', '863');
insert into Theatre (tname, address, zip) values ('Quo Lux', '98 Ludington Center', '45936');
insert into Theatre (tname, address, zip) values ('Mat Lam Tam', '395 Karstens Parkway', '14');
insert into Theatre (tname, address, zip) values ('Stringtough', '4 Dennis Road', '04');
insert into Theatre (tname, address, zip) values ('Aerified', '01740 Arizona Crossing', '905');
insert into Theatre (tname, address, zip) values ('Wrapsafe', '2619 Talisman Way', '77089');
insert into Theatre (tname, address, zip) values ('Pannier', '1 Menomonie Plaza', '7');
insert into Theatre (tname, address, zip) values ('Solarbreeze', '2 Dottie Street', '96');
insert into Theatre (tname, address, zip) values ('Zontrax', '420 Prentice Trail', '544');
insert into Theatre (tname, address, zip) values ('Hatity', '55 Green Ridge Avenue', '3324');
insert into Theatre (tname, address, zip) values ('Treeflex', '898 Bunting Center', '74779');
insert into Theatre (tname, address, zip) values ('Tres-Zap', '27549 Vera Street', '196');
insert into Theatre (tname, address, zip) values ('Biodex', '54 Russell Terrace', '887');
insert into Theatre (tname, address, zip) values ('Tin', '1659 Fisk Junction', '959');
insert into Theatre (tname, address, zip) values ('Viva', '4 Schiller Place', '2');
insert into Theatre (tname, address, zip) values ('Fixflex', '71 5th Pass', '5');
insert into Theatre (tname, address, zip) values ('Job', '8850 Forest Run Circle', '0');
insert into Theatre (tname, address, zip) values ('Temp', '50 Sloan Place', '09');
insert into Theatre (tname, address, zip) values ('Sub-Ex', '66 Thackeray Circle', '5038');
insert into Theatre (tname, address, zip) values ('Transcof', '5 Miller Parkway', '179');
insert into Theatre (tname, address, zip) values ('Transcof', '7 Sutteridge Point', '7781');
insert into Theatre (tname, address, zip) values ('Opela', '8 Katie Circle', '2');
insert into Theatre (tname, address, zip) values ('Domainer', '0 Warrior Trail', '7045');
insert into Theatre (tname, address, zip) values ('Zoolab', '4030 Butternut Point', '527');
insert into Theatre (tname, address, zip) values ('Flowdesk', '181 Mcguire Lane', '2');
insert into Theatre (tname, address, zip) values ('Zoolab', '1097 Westend Plaza', '9343');
insert into Theatre (tname, address, zip) values ('Vagram', '25 Scott Court', '1285');
insert into Theatre (tname, address, zip) values ('Transcof', '74 Jenna Street', '54389');
insert into Theatre (tname, address, zip) values ('Y-find', '837 Dapin Court', '318');
insert into Theatre (tname, address, zip) values ('Voltsillam', '5110 8th Road', '44');
insert into Theatre (tname, address, zip) values ('Ventosanzap', '0 Longview Pass', '52330');
insert into Theatre (tname, address, zip) values ('Latlux', '1 Veith Trail', '15790');
insert into Theatre (tname, address, zip) values ('Holdlamis', '159 Vermont Center', '9897');
insert into Theatre (tname, address, zip) values ('Viva', '61122 Bultman Parkway', '6');
insert into Theatre (tname, address, zip) values ('Bitchip', '77014 Bultman Parkway', '0470');
insert into Theatre (tname, address, zip) values ('Voltsillam', '16 Morning Junction', '00956');
insert into Theatre (tname, address, zip) values ('Zontrax', '7 Orin Alley', '730');
insert into Theatre (tname, address, zip) values ('Otcom', '9 Corscot Park', '0711');
insert into Theatre (tname, address, zip) values ('Span', '14 Crest Line Street', '2708');
insert into Theatre (tname, address, zip) values ('Zamit', '7565 Pawling Junction', '15');
insert into Theatre (tname, address, zip) values ('Greenlam', '52 Carberry Avenue', '92');
insert into Theatre (tname, address, zip) values ('Y-Solowarm', '4 Artisan Trail', '4');
insert into Theatre (tname, address, zip) values ('Prodder', '38736 Iowa Place', '58107');
insert into Theatre (tname, address, zip) values ('Transcof', '5908 Old Shore Road', '97');
insert into Theatre (tname, address, zip) values ('Fix San', '6714 Duke Center', '87');
insert into Theatre (tname, address, zip) values ('Zoolab', '1 Burning Wood Junction', '807');
insert into Theatre (tname, address, zip) values ('Cookley', '0611 Kropf Circle', '00160');
insert into Theatre (tname, address, zip) values ('Sonsing', '2 Longview Trail', '39');
insert into Theatre (tname, address, zip) values ('Keylex', '3377 Union Drive', '328');
insert into Theatre (tname, address, zip) values ('Y-Solowarm', '175 Thackeray Parkway', '04657');
insert into Theatre (tname, address, zip) values ('Bitchip', '566 Spenser Lane', '916');
insert into Theatre (tname, address, zip) values ('Stim', '32 Oxford Crossing', '60');
insert into Theatre (tname, address, zip) values ('Duobam', '46 Oxford Circle', '90');
insert into Theatre (tname, address, zip) values ('Andalax', '5 Northwestern Terrace', '4292');
insert into Theatre (tname, address, zip) values ('Fintone', '0352 Westend Point', '06');
insert into Theatre (tname, address, zip) values ('Ronstring', '974 Riverside Center', '15');
insert into Theatre (tname, address, zip) values ('Tres-Zap', '22 Arrowood Point', '1715');
insert into Theatre (tname, address, zip) values ('Voltsillam', '8 Morning Center', '09313');
insert into Theatre (tname, address, zip) values ('Latlux', '076 Park Meadow Plaza', '8659');
insert into Theatre (tname, address, zip) values ('Gembucket', '65 Acker Alley', '0582');
insert into Theatre (tname, address, zip) values ('Tin', '552 1st Circle', '3');
insert into Theatre (tname, address, zip) values ('Span', '8 Quincy Circle', '972');
insert into Theatre (tname, address, zip) values ('Zaam-Dox', '7665 Scofield Lane', '2');
insert into Theatre (tname, address, zip) values ('Cardify', '934 Swallow Circle', '28');
insert into Theatre (tname, address, zip) values ('It', '8 Mandrake Crossing', '8061');
insert into Theatre (tname, address, zip) values ('Fintone', '25829 2nd Circle', '9');
insert into Theatre (tname, address, zip) values ('Zathin', '45612 Welch Avenue', '64');
insert into Theatre (tname, address, zip) values ('Rank', '742 Mayfield Court', '4');
insert into Theatre (tname, address, zip) values ('Solarbreeze', '66 Hoepker Park', '330');
insert into Theatre (tname, address, zip) values ('Temp', '393 Shopko Place', '82164');
insert into Theatre (tname, address, zip) values ('Zontrax', '9027 Kinsman Road', '0');
insert into Theatre (tname, address, zip) values ('Alpha', '021 Rutledge Circle', '791');
insert into Theatre (tname, address, zip) values ('Tresom', '9081 Hermina Court', '758');
insert into Theatre (tname, address, zip) values ('Regrant', '7 Di Loreto Pass', '4628');
insert into Theatre (tname, address, zip) values ('Temp', '81703 Drewry Terrace', '8064');
insert into Theatre (tname, address, zip) values ('Holdlamis', '8 Ramsey Way', '5878');
insert into Theatre (tname, address, zip) values ('Tampflex', '88 Corben Parkway', '3452');
insert into Theatre (tname, address, zip) values ('Konklux', '91045 Maple Wood Trail', '752');
insert into Theatre (tname, address, zip) values ('Voltsillam', '87 Thackeray Place', '454');
insert into Theatre (tname, address, zip) values ('Alphazap', '49228 Glacier Hill Street', '6933');
insert into Theatre (tname, address, zip) values ('Solarbreeze', '116 Hanson Avenue', '75');
insert into Theatre (tname, address, zip) values ('Zamit', '32 Brentwood Junction', '83');
insert into Theatre (tname, address, zip) values ('Bytecard', '12 Mayfield Junction', '1478');
insert into Theatre (tname, address, zip) values ('Stringtough', '26 Glacier Hill Point', '94487');
insert into Theatre (tname, address, zip) values ('Kanlam', '8 Northview Crossing', '7835');
insert into Theatre (tname, address, zip) values ('Job', '0 Schmedeman Avenue', '58');
insert into Theatre (tname, address, zip) values ('Y-find', '1 Mendota Road', '43531');
insert into Theatre (tname, address, zip) values ('Sub-Ex', '1 Swallow Park', '8594');
insert into Theatre (tname, address, zip) values ('Redhold', '15843 Del Sol Junction', '09894');
insert into Theatre (tname, address, zip) values ('Bigtax', '3635 Barnett Crossing', '48');
insert into Theatre (tname, address, zip) values ('Sonair', '50 La Follette Court', '9');
insert into Theatre (tname, address, zip) values ('Y-Solowarm', '903 Veith Avenue', '8');
insert into Theatre (tname, address, zip) values ('Overhold', '1539 Colorado Point', '69');
insert into Theatre (tname, address, zip) values ('Kanlam', '1100 Hazelcrest Way', '2');
insert into Theatre (tname, address, zip) values ('Redhold', '40 Mallard Pass', '81262');
insert into Theatre (tname, address, zip) values ('Andalax', '12 Fieldstone Park', '0269');
insert into Theatre (tname, address, zip) values ('Ronstring', '83 Mosinee Plaza', '7409');
insert into Theatre (tname, address, zip) values ('Flexidy', '2 Namekagon Lane', '2744');
insert into Theatre (tname, address, zip) values ('Pannier', '9 Westerfield Junction', '14');
insert into Theatre (tname, address, zip) values ('Greenlam', '981 Pierstorff Plaza', '58');
insert into Theatre (tname, address, zip) values ('Ventosanzap', '7526 Sunnyside Place', '22791');
insert into Theatre (tname, address, zip) values ('Bitchip', '16557 Forest Run Alley', '57406');
insert into Theatre (tname, address, zip) values ('Temp', '6520 Corscot Road', '73527');
insert into Theatre (tname, address, zip) values ('Quo Lux', '93759 Mccormick Trail', '9963');
insert into Theatre (tname, address, zip) values ('Quo Lux', '5 1st Plaza', '15');
insert into Theatre (tname, address, zip) values ('Prodder', '23 Elka Way', '97240');
insert into Theatre (tname, address, zip) values ('Flowdesk', '50 Laurel Alley', '7931');
insert into Theatre (tname, address, zip) values ('Sonsing', '7891 Bultman Lane', '987');
insert into Theatre (tname, address, zip) values ('Viva', '47396 Scoville Street', '0770');
insert into Theatre (tname, address, zip) values ('Andalax', '4198 Sommers Terrace', '3356');
insert into Theatre (tname, address, zip) values ('Tres-Zap', '740 Montana Pass', '90137');
insert into Theatre (tname, address, zip) values ('Flexidy', '1105 Old Gate Court', '9');
insert into Theatre (tname, address, zip) values ('Toughjoyfax', '90 Stang Hill', '86401');
insert into Theatre (tname, address, zip) values ('Veribet', '6 Lake View Pass', '006');
insert into Theatre (tname, address, zip) values ('Flexidy', '233 Village Terrace', '26');
insert into Theatre (tname, address, zip) values ('Y-find', '4304 Old Shore Hill', '44');
insert into Theatre (tname, address, zip) values ('Otcom', '07378 Westridge Center', '3788');
insert into Theatre (tname, address, zip) values ('Overhold', '50607 Susan Court', '6');
insert into Theatre (tname, address, zip) values ('Treeflex', '430 Rusk Road', '3161');
insert into Theatre (tname, address, zip) values ('Cookley', '9353 Burrows Plaza', '205');
insert into Theatre (tname, address, zip) values ('Redhold', '6627 Rockefeller Center', '5880');
insert into Theatre (tname, address, zip) values ('Overhold', '2307 Huxley Pass', '6');
insert into Theatre (tname, address, zip) values ('Lotlux', '62905 Lien Trail', '61898');
insert into Theatre (tname, address, zip) values ('Alpha', '020 Del Mar Avenue', '27');
insert into Theatre (tname, address, zip) values ('Overhold', '12 Roth Avenue', '39');
insert into Theatre (tname, address, zip) values ('Fixflex', '4862 Northview Hill', '1');
insert into Theatre (tname, address, zip) values ('Sonsing', '99771 Graedel Plaza', '601');
insert into Theatre (tname, address, zip) values ('Zaam-Dox', '1 High Crossing Way', '68914');
insert into Theatre (tname, address, zip) values ('Zamit', '518 Autumn Leaf Place', '9959');
insert into Theatre (tname, address, zip) values ('Bitwolf', '366 Londonderry Terrace', '2');
insert into Theatre (tname, address, zip) values ('Stim', '2 Golf Circle', '2484');
insert into Theatre (tname, address, zip) values ('Quo Lux', '0 Dunning Way', '6278');
insert into Theatre (tname, address, zip) values ('Opela', '737 North Trail', '78');
insert into Theatre (tname, address, zip) values ('Voltsillam', '56 Golf Crossing', '0');
insert into Theatre (tname, address, zip) values ('Domainer', '6 American Ash Street', '529');
insert into Theatre (tname, address, zip) values ('Zontrax', '66820 Becker Alley', '991');
insert into Theatre (tname, address, zip) values ('Matsoft', '90 Stone Corner Crossing', '221');
insert into Theatre (tname, address, zip) values ('Biodex', '7 Killdeer Point', '2636');
insert into Theatre (tname, address, zip) values ('Y-Solowarm', '8 Bowman Pass', '92536');
insert into Theatre (tname, address, zip) values ('Alpha', '11114 La Follette Plaza', '94784');
insert into Theatre (tname, address, zip) values ('Bitwolf', '1 Starling Park', '251');
insert into Theatre (tname, address, zip) values ('Wrapsafe', '0 Banding Drive', '75467');
insert into Theatre (tname, address, zip) values ('Gembucket', '69 Waubesa Place', '5');
insert into Theatre (tname, address, zip) values ('Temp', '70 Meadow Valley Crossing', '7');
insert into Theatre (tname, address, zip) values ('Viva', '75 Cody Place', '6321');
insert into Theatre (tname, address, zip) values ('Asoka', '51 Hooker Park', '3005');
insert into Theatre (tname, address, zip) values ('Holdlamis', '0707 Buena Vista Pass', '7568');
insert into Theatre (tname, address, zip) values ('Matsoft', '26 Graceland Crossing', '36');
insert into Theatre (tname, address, zip) values ('Kanlam', '59 Di Loreto Junction', '2');
insert into Theatre (tname, address, zip) values ('Konklab', '593 Corry Street', '546');
insert into Theatre (tname, address, zip) values ('Voltsillam', '776 Schiller Road', '1556');
insert into Theatre (tname, address, zip) values ('Fintone', '250 Colorado Crossing', '0746');
insert into Theatre (tname, address, zip) values ('Hatity', '6 Hooker Avenue', '6');
insert into Theatre (tname, address, zip) values ('Greenlam', '95305 Nevada Drive', '88857');
insert into Theatre (tname, address, zip) values ('Quo Lux', '24339 Southridge Pass', '654');
insert into Theatre (tname, address, zip) values ('Trippledex', '412 Donald Road', '7');
insert into Theatre (tname, address, zip) values ('Cookley', '7495 Dovetail Circle', '32316');
insert into Theatre (tname, address, zip) values ('Fixflex', '48 Little Fleur Trail', '1');
insert into Theatre (tname, address, zip) values ('Konklux', '3322 Loeprich Pass', '4742');
insert into Theatre (tname, address, zip) values ('Zoolab', '05896 Crescent Oaks Street', '977');
insert into Theatre (tname, address, zip) values ('Sub-Ex', '49892 Dunning Place', '480');
insert into Theatre (tname, address, zip) values ('Overhold', '89 Weeping Birch Pass', '8');
insert into Theatre (tname, address, zip) values ('Home Ing', '88369 Summerview Street', '9');
insert into Theatre (tname, address, zip) values ('Temp', '8008 Dryden Place', '7');
insert into Theatre (tname, address, zip) values ('Zaam-Dox', '46178 Judy Plaza', '777');
insert into Theatre (tname, address, zip) values ('Tres-Zap', '6470 Northport Point', '33430');
insert into Theatre (tname, address, zip) values ('Matsoft', '8099 Rockefeller Junction', '0');
insert into Theatre (tname, address, zip) values ('Tempsoft', '7826 Prentice Way', '29164');
insert into Theatre (tname, address, zip) values ('Tresom', '6218 Dorton Point', '132');
insert into Theatre (tname, address, zip) values ('Domainer', '87 Arkansas Center', '28');
insert into Theatre (tname, address, zip) values ('Lotlux', '68058 Schlimgen Park', '53');
insert into Theatre (tname, address, zip) values ('Lotstring', '24 Gerald Crossing', '24617');
insert into Theatre (tname, address, zip) values ('Zamit', '516 Grover Lane', '87');
insert into Theatre (tname, address, zip) values ('Bytecard', '44691 Express Point', '8880');
insert into Theatre (tname, address, zip) values ('Fintone', '24019 Vermont Street', '68');
insert into Theatre (tname, address, zip) values ('Kanlam', '6 Iowa Circle', '3613');
insert into Theatre (tname, address, zip) values ('Stim', '07 Caliangt Alley', '05');
insert into Theatre (tname, address, zip) values ('Tresom', '2761 Alpine Junction', '1');
insert into Theatre (tname, address, zip) values ('Stringtough', '87 Roxbury Point', '308');
insert into Theatre (tname, address, zip) values ('Rank', '28520 Forest Point', '82');
insert into Theatre (tname, address, zip) values ('Namfix', '1 Anhalt Terrace', '1399');
insert into Theatre (tname, address, zip) values ('Vagram', '7352 Thompson Avenue', '58');
insert into Theatre (tname, address, zip) values ('Y-Solowarm', '04 Green Ridge Circle', '169');
insert into Theatre (tname, address, zip) values ('Bitchip', '3397 Porter Terrace', '60');
insert into Theatre (tname, address, zip) values ('Zathin', '76637 Swallow Way', '830');
insert into Theatre (tname, address, zip) values ('Zaam-Dox', '16 Forest Dale Avenue', '4404');
insert into Theatre (tname, address, zip) values ('Opela', '425 Evergreen Terrace', '7');
insert into Theatre (tname, address, zip) values ('Zaam-Dox', '302 Claremont Drive', '331');
insert into Theatre (tname, address, zip) values ('Zaam-Dox', '45684 Acker Crossing', '3');
insert into Theatre (tname, address, zip) values ('Opela', '1570 Acker Terrace', '29249');
insert into Theatre (tname, address, zip) values ('Solarbreeze', '27915 Sloan Alley', '1211');
insert into Theatre (tname, address, zip) values ('Sonsing', '92 Manitowish Parkway', '74');
insert into Theatre (tname, address, zip) values ('Bitwolf', '349 Talmadge Parkway', '08077');
insert into Theatre (tname, address, zip) values ('Stronghold', '9338 Garrison Crossing', '984');
insert into Theatre (tname, address, zip) values ('Flexidy', '65 Rusk Way', '57');
insert into Theatre (tname, address, zip) values ('Transcof', '4152 Rowland Point', '104');
insert into Theatre (tname, address, zip) values ('Mat Lam Tam', '1 International Avenue', '1286');
insert into Theatre (tname, address, zip) values ('Ventosanzap', '30 Hermina Alley', '92');
insert into Theatre (tname, address, zip) values ('Trippledex', '41 Pleasure Point', '01');
insert into Theatre (tname, address, zip) values ('Stronghold', '51838 Anhalt Place', '0594');
insert into Theatre (tname, address, zip) values ('Keylex', '88 Amoth Circle', '866');
insert into Theatre (tname, address, zip) values ('Fintone', '4523 Maple Parkway', '89');
insert into Theatre (tname, address, zip) values ('Lotstring', '419 Lakewood Trail', '859');
insert into Theatre (tname, address, zip) values ('Greenlam', '559 Arrowood Park', '837');
insert into Theatre (tname, address, zip) values ('Trippledex', '41680 Golf Course Pass', '0984');
insert into Theatre (tname, address, zip) values ('Gembucket', '3787 Columbus Center', '6');
insert into Theatre (tname, address, zip) values ('Greenlam', '61355 Mifflin Terrace', '5');
insert into Theatre (tname, address, zip) values ('Regrant', '7 Melody Terrace', '3361');
insert into Theatre (tname, address, zip) values ('Regrant', '670 Birchwood Court', '69574');
insert into Theatre (tname, address, zip) values ('Opela', '588 Brickson Park Parkway', '6444');
insert into Theatre (tname, address, zip) values ('Subin', '3 Lakewood Drive', '47273');
insert into Theatre (tname, address, zip) values ('Tin', '23106 Vera Avenue', '56');
insert into Theatre (tname, address, zip) values ('Alphazap', '94 Macpherson Way', '49');
insert into Theatre (tname, address, zip) values ('Ronstring', '47430 Golf Avenue', '64019');
insert into Theatre (tname, address, zip) values ('Alpha', '82660 Schmedeman Pass', '5795');
insert into Theatre (tname, address, zip) values ('Fixflex', '884 Service Drive', '2286');
insert into Theatre (tname, address, zip) values ('Hatity', '90695 Hovde Street', '92655');
insert into Theatre (tname, address, zip) values ('Greenlam', '47 Veith Park', '60');
insert into Theatre (tname, address, zip) values ('Zontrax', '75386 Grasskamp Avenue', '8');
insert into Theatre (tname, address, zip) values ('Andalax', '116 Washington Court', '68');
insert into Theatre (tname, address, zip) values ('Prodder', '75 Oak Valley Junction', '00');
insert into Theatre (tname, address, zip) values ('Prodder', '2624 Cambridge Lane', '7');
insert into Theatre (tname, address, zip) values ('Keylex', '611 School Crossing', '6704');
insert into Theatre (tname, address, zip) values ('Duobam', '7383 Nancy Way', '51');
insert into Theatre (tname, address, zip) values ('Sonsing', '49510 Bultman Terrace', '7');
insert into Theatre (tname, address, zip) values ('Kanlam', '03920 Calypso Center', '8557');
insert into Theatre (tname, address, zip) values ('Bitwolf', '14 Luster Street', '811');
insert into Theatre (tname, address, zip) values ('Namfix', '5870 Morningstar Plaza', '803');
insert into Theatre (tname, address, zip) values ('Duobam', '2615 Colorado Hill', '43');
insert into Theatre (tname, address, zip) values ('Sub-Ex', '68 Duke Hill', '6');
insert into Theatre (tname, address, zip) values ('Span', '3 Stoughton Park', '2');
insert into Theatre (tname, address, zip) values ('Daltfresh', '77175 Sunfield Terrace', '55289');
insert into Theatre (tname, address, zip) values ('Konklab', '805 Crowley Center', '4435');
insert into Theatre (tname, address, zip) values ('Overhold', '4 Redwing Crossing', '174');
insert into Theatre (tname, address, zip) values ('Tresom', '61 Dexter Parkway', '7323');
insert into Theatre (tname, address, zip) values ('Tampflex', '5 Bartelt Circle', '9');
insert into Theatre (tname, address, zip) values ('Holdlamis', '64 Waubesa Center', '40418');
insert into Theatre (tname, address, zip) values ('Bitwolf', '56 Chive Parkway', '86665');
insert into Theatre (tname, address, zip) values ('Y-find', '816 Orin Parkway', '586');
insert into Theatre (tname, address, zip) values ('Regrant', '8 Daystar Park', '50311');
insert into Theatre (tname, address, zip) values ('Keylex', '866 Graedel Circle', '9');
insert into Theatre (tname, address, zip) values ('Fix San', '24 Derek Plaza', '924');
insert into Theatre (tname, address, zip) values ('Voltsillam', '7 Vera Court', '4');
insert into Theatre (tname, address, zip) values ('Lotstring', '4811 Gulseth Junction', '5066');
insert into Theatre (tname, address, zip) values ('Bitchip', '89147 Summit Crossing', '4908');
insert into Theatre (tname, address, zip) values ('Hatity', '994 Sunfield Avenue', '091');
insert into Theatre (tname, address, zip) values ('Tin', '14622 Morrow Trail', '89324');
insert into Theatre (tname, address, zip) values ('Tin', '60 Beilfuss Drive', '8515');
insert into Theatre (tname, address, zip) values ('Tresom', '20 Kingsford Court', '91640');
insert into Theatre (tname, address, zip) values ('Aerified', '1 Canary Alley', '07');
insert into Theatre (tname, address, zip) values ('Prodder', '6900 Vera Terrace', '8');
insert into Theatre (tname, address, zip) values ('Biodex', '49 Bultman Crossing', '470');
insert into Theatre (tname, address, zip) values ('Namfix', '323 Pankratz Point', '34');
insert into Theatre (tname, address, zip) values ('Konklab', '49667 Bay Trail', '1');
insert into Theatre (tname, address, zip) values ('Temp', '3922 Monica Street', '1770');
insert into Theatre (tname, address, zip) values ('Cardify', '1 David Road', '931');
insert into Theatre (tname, address, zip) values ('Toughjoyfax', '772 Harper Court', '3');
insert into Theatre (tname, address, zip) values ('Wrapsafe', '68 Sage Plaza', '2299');
insert into Theatre (tname, address, zip) values ('Matsoft', '2004 Nevada Center', '7');
insert into Theatre (tname, address, zip) values ('Job', '3623 Kim Road', '2565');
insert into Theatre (tname, address, zip) values ('Bigtax', '183 Sutteridge Center', '4560');
insert into Theatre (tname, address, zip) values ('Cardguard', '4108 Northport Center', '219');
insert into Theatre (tname, address, zip) values ('Pannier', '39 Red Cloud Park', '1');
insert into Theatre (tname, address, zip) values ('Bamity', '1 Mockingbird Park', '51');
insert into Theatre (tname, address, zip) values ('Subin', '83494 Shelley Alley', '6');
insert into Theatre (tname, address, zip) values ('Alpha', '5285 Barby Junction', '0244');
insert into Theatre (tname, address, zip) values ('Voyatouch', '2 Sherman Junction', '0062');
insert into Theatre (tname, address, zip) values ('Voltsillam', '67267 Fairfield Way', '551');
insert into Theatre (tname, address, zip) values ('Subin', '704 Springview Pass', '516');
insert into Theatre (tname, address, zip) values ('Sonsing', '00506 Corscot Parkway', '8');
insert into Theatre (tname, address, zip) values ('Span', '400 Green Ridge Center', '6');
insert into Theatre (tname, address, zip) values ('Bitwolf', '77 Blackbird Way', '58');
insert into Theatre (tname, address, zip) values ('Andalax', '95087 Gateway Hill', '930');
insert into Theatre (tname, address, zip) values ('Hatity', '4 6th Court', '0');
insert into Theatre (tname, address, zip) values ('Domainer', '6 Mayfield Road', '9');
insert into Theatre (tname, address, zip) values ('Bitwolf', '7 4th Street', '522');
insert into Theatre (tname, address, zip) values ('Bitchip', '37 Northland Avenue', '54');
insert into Theatre (tname, address, zip) values ('Latlux', '73 Donald Crossing', '8');
insert into Theatre (tname, address, zip) values ('Alpha', '320 Basil Point', '462');
insert into Theatre (tname, address, zip) values ('Alpha', '94 Bunker Hill Hill', '4');
insert into Theatre (tname, address, zip) values ('Zaam-Dox', '08265 West Place', '290');
insert into Theatre (tname, address, zip) values ('Ventosanzap', '27739 Express Drive', '53');
insert into Theatre (tname, address, zip) values ('Trippledex', '5661 Hansons Circle', '39204');
insert into Theatre (tname, address, zip) values ('Ventosanzap', '9 Gateway Terrace', '67');
insert into Theatre (tname, address, zip) values ('Alpha', '93 Swallow Junction', '19');
insert into Theatre (tname, address, zip) values ('Tampflex', '9769 Paget Center', '2217');
insert into Theatre (tname, address, zip) values ('Duobam', '2 Crownhardt Hill', '794');
insert into Theatre (tname, address, zip) values ('It', '5 Golf View Parkway', '9');
insert into Theatre (tname, address, zip) values ('Bitwolf', '0958 Barnett Road', '96');
insert into Theatre (tname, address, zip) values ('Zathin', '3085 Monterey Pass', '652');
insert into Theatre (tname, address, zip) values ('Temp', '9 Hovde Alley', '238');
insert into Theatre (tname, address, zip) values ('Sonsing', '31 Westridge Park', '650');
insert into Theatre (tname, address, zip) values ('Stronghold', '408 Rockefeller Way', '8388');
insert into Theatre (tname, address, zip) values ('Opela', '1 Stang Place', '1');
insert into Theatre (tname, address, zip) values ('Daltfresh', '0968 Division Hill', '194');
insert into Theatre (tname, address, zip) values ('Biodex', '983 Drewry Trail', '2');
insert into Theatre (tname, address, zip) values ('Namfix', '39 Arrowood Avenue', '8745');
insert into Theatre (tname, address, zip) values ('Konklab', '5 Steensland Avenue', '453');
insert into Theatre (tname, address, zip) values ('Sonsing', '42 Chinook Trail', '038');
insert into Theatre (tname, address, zip) values ('Tres-Zap', '4483 Basil Center', '73962');
insert into Theatre (tname, address, zip) values ('Fintone', '882 Graedel Circle', '7856');
insert into Theatre (tname, address, zip) values ('Solarbreeze', '56 Mccormick Alley', '6');
insert into Theatre (tname, address, zip) values ('Viva', '8 Waxwing Junction', '9050');
insert into Theatre (tname, address, zip) values ('Stronghold', '34 Sloan Court', '87');
insert into Theatre (tname, address, zip) values ('Lotlux', '362 Holmberg Parkway', '1');
insert into Theatre (tname, address, zip) values ('Fixflex', '091 Sage Alley', '04495');
insert into Theatre (tname, address, zip) values ('Aerified', '61138 Corscot Circle', '09');
insert into Theatre (tname, address, zip) values ('Stim', '599 East Trail', '4385');
insert into Theatre (tname, address, zip) values ('Toughjoyfax', '122 Arrowood Road', '37423');
insert into Theatre (tname, address, zip) values ('Tresom', '2185 Lerdahl Circle', '694');
insert into Theatre (tname, address, zip) values ('Otcom', '4 Bowman Hill', '82895');
insert into Theatre (tname, address, zip) values ('Span', '9336 Namekagon Place', '1989');
insert into Theatre (tname, address, zip) values ('Wrapsafe', '99 Becker Terrace', '53');
insert into Theatre (tname, address, zip) values ('Voyatouch', '47 Homewood Crossing', '9');
insert into Theatre (tname, address, zip) values ('Fintone', '7 Debs Junction', '6');
insert into Theatre (tname, address, zip) values ('Toughjoyfax', '901 Graceland Street', '28');
insert into Theatre (tname, address, zip) values ('Y-find', '50 Vidon Plaza', '8');
insert into Theatre (tname, address, zip) values ('Regrant', '4189 Prentice Junction', '5354');
insert into Theatre (tname, address, zip) values ('Tempsoft', '06 Lindbergh Point', '6');
insert into Theatre (tname, address, zip) values ('Fintone', '542 Merrick Lane', '44520');
insert into Theatre (tname, address, zip) values ('Matsoft', '25304 Elka Lane', '606');
insert into Theatre (tname, address, zip) values ('Solarbreeze', '1830 Norway Maple Road', '38521');
insert into Theatre (tname, address, zip) values ('Regrant', '9 Heath Junction', '7');
insert into Theatre (tname, address, zip) values ('Gembucket', '970 Bultman Road', '7408');
insert into Theatre (tname, address, zip) values ('Fix San', '4 Monument Alley', '5');
insert into Theatre (tname, address, zip) values ('Fix San', '2815 Dottie Park', '0635');
insert into Theatre (tname, address, zip) values ('Bytecard', '35 Kipling Avenue', '012');
insert into Theatre (tname, address, zip) values ('Namfix', '42 Katie Alley', '490');
insert into Theatre (tname, address, zip) values ('Fix San', '821 Union Road', '780');
insert into Theatre (tname, address, zip) values ('Domainer', '936 Vahlen Junction', '5130');
insert into Theatre (tname, address, zip) values ('Bitchip', '3 Brentwood Drive', '8861');
insert into Theatre (tname, address, zip) values ('Holdlamis', '25694 Elmside Lane', '24391');
insert into Theatre (tname, address, zip) values ('Alphazap', '1007 Monica Avenue', '6');
insert into Theatre (tname, address, zip) values ('Zaam-Dox', '621 Cottonwood Alley', '9');
insert into Theatre (tname, address, zip) values ('Vagram', '6 Holmberg Park', '75089');
insert into Theatre (tname, address, zip) values ('Sub-Ex', '5 Talmadge Street', '6');
insert into Theatre (tname, address, zip) values ('Voyatouch', '0 Nevada Terrace', '75');
insert into Theatre (tname, address, zip) values ('Flexidy', '38 Nancy Avenue', '3258');
insert into Theatre (tname, address, zip) values ('Kanlam', '679 Morning Trail', '90');
insert into Theatre (tname, address, zip) values ('Andalax', '8 Mendota Park', '367');
insert into Theatre (tname, address, zip) values ('Treeflex', '323 Thackeray Center', '103');
insert into Theatre (tname, address, zip) values ('Tampflex', '978 Westend Avenue', '27');
insert into Theatre (tname, address, zip) values ('Keylex', '76735 Iowa Avenue', '87');
insert into Theatre (tname, address, zip) values ('Opela', '30 Merrick Pass', '5');
insert into Theatre (tname, address, zip) values ('Temp', '01 Carioca Place', '04');
insert into Theatre (tname, address, zip) values ('Ronstring', '7141 Reindahl Crossing', '1');
insert into Theatre (tname, address, zip) values ('Tempsoft', '2 Forest Dale Street', '0014');
insert into Theatre (tname, address, zip) values ('Fixflex', '64 Fallview Terrace', '86');
insert into Theatre (tname, address, zip) values ('Sub-Ex', '55856 Lien Junction', '34957');
insert into Theatre (tname, address, zip) values ('Kanlam', '53774 Sullivan Circle', '141');
insert into Theatre (tname, address, zip) values ('Y-find', '110 Tennyson Court', '1422');
insert into Theatre (tname, address, zip) values ('Domainer', '975 Hooker Park', '949');
insert into Theatre (tname, address, zip) values ('Opela', '0 Nobel Point', '971');
insert into Theatre (tname, address, zip) values ('Stronghold', '9 Warner Plaza', '77');
insert into Theatre (tname, address, zip) values ('Prodder', '6200 Lukken Center', '222');
insert into Theatre (tname, address, zip) values ('Cardguard', '770 Lunder Alley', '0969');
insert into Theatre (tname, address, zip) values ('Cookley', '2 Victoria Road', '79898');
insert into Theatre (tname, address, zip) values ('Konklux', '91157 Pearson Crossing', '171');
insert into Theatre (tname, address, zip) values ('Lotlux', '2 Summerview Point', '37486');
insert into Theatre (tname, address, zip) values ('Y-Solowarm', '5664 Monica Point', '74');
insert into Theatre (tname, address, zip) values ('Stringtough', '8517 Sutteridge Court', '0235');
insert into Theatre (tname, address, zip) values ('Rank', '9 Old Gate Center', '7284');
insert into Theatre (tname, address, zip) values ('Redhold', '4241 Memorial Trail', '883');
insert into Theatre (tname, address, zip) values ('Flexidy', '2212 Butterfield Avenue', '595');
insert into Theatre (tname, address, zip) values ('Duobam', '6 Cottonwood Hill', '04335');
insert into Theatre (tname, address, zip) values ('Zaam-Dox', '3 Fieldstone Trail', '05827');
insert into Theatre (tname, address, zip) values ('Tempsoft', '79439 Corscot Place', '94');
insert into Theatre (tname, address, zip) values ('Bitwolf', '19576 Buena Vista Center', '11050');
insert into Theatre (tname, address, zip) values ('Bigtax', '507 Ronald Regan Plaza', '062');
insert into Theatre (tname, address, zip) values ('Latlux', '7821 Onsgard Park', '4');
insert into Theatre (tname, address, zip) values ('Y-find', '65539 Harbort Junction', '655');
insert into Theatre (tname, address, zip) values ('Holdlamis', '332 Golf Alley', '368');
insert into Theatre (tname, address, zip) values ('Tresom', '593 Rieder Road', '001');
insert into Theatre (tname, address, zip) values ('Kanlam', '1547 Sunbrook Road', '0');
insert into Theatre (tname, address, zip) values ('Flowdesk', '776 Mayer Street', '7');
insert into Theatre (tname, address, zip) values ('Fintone', '6 Stone Corner Circle', '41749');
insert into Theatre (tname, address, zip) values ('Rank', '6 Bellgrove Junction', '76');
insert into Theatre (tname, address, zip) values ('Voyatouch', '66 Dunning Road', '501');
insert into Theatre (tname, address, zip) values ('Konklux', '2657 Norway Maple Center', '136');
insert into Theatre (tname, address, zip) values ('Hatity', '53083 Autumn Leaf Street', '9');
insert into Theatre (tname, address, zip) values ('Wrapsafe', '97 Sycamore Crossing', '3561');
insert into Theatre (tname, address, zip) values ('Bytecard', '508 West Circle', '0');
insert into Theatre (tname, address, zip) values ('Namfix', '0 Talmadge Circle', '786');
insert into Theatre (tname, address, zip) values ('Toughjoyfax', '60880 Cardinal Junction', '97612');
insert into Theatre (tname, address, zip) values ('Stronghold', '521 Oneill Point', '38');
insert into Theatre (tname, address, zip) values ('Zaam-Dox', '57713 Schurz Terrace', '3');
insert into Theatre (tname, address, zip) values ('Bytecard', '747 Del Sol Pass', '649');
insert into Theatre (tname, address, zip) values ('Otcom', '6 Del Sol Parkway', '99');
insert into Theatre (tname, address, zip) values ('Domainer', '7 Lyons Place', '3');
insert into Theatre (tname, address, zip) values ('Lotlux', '7 Granby Road', '1');
insert into Theatre (tname, address, zip) values ('Tres-Zap', '50000 Eagle Crest Pass', '312');
insert into Theatre (tname, address, zip) values ('Fixflex', '878 Portage Junction', '0');
insert into Theatre (tname, address, zip) values ('Job', '3641 Forster Drive', '82018');
insert into Theatre (tname, address, zip) values ('Flexidy', '48 Tennyson Lane', '0397');
insert into Theatre (tname, address, zip) values ('Sonsing', '2 Valley Edge Junction', '31503');
insert into Theatre (tname, address, zip) values ('Tresom', '807 Northridge Park', '3525');
insert into Theatre (tname, address, zip) values ('Aerified', '9223 Transport Parkway', '126');
insert into Theatre (tname, address, zip) values ('Veribet', '546 Buena Vista Junction', '88384');
insert into Theatre (tname, address, zip) values ('Subin', '3595 Northview Junction', '9');
insert into Theatre (tname, address, zip) values ('Zathin', '929 Bluejay Crossing', '23331');
insert into Theatre (tname, address, zip) values ('Bytecard', '0441 Bonner Trail', '93');
insert into Theatre (tname, address, zip) values ('Cookley', '163 Derek Hill', '8');
insert into Theatre (tname, address, zip) values ('Daltfresh', '21998 Valley Edge Way', '59398');
insert into Theatre (tname, address, zip) values ('Greenlam', '9128 Karstens Center', '2324');
insert into Theatre (tname, address, zip) values ('Pannier', '38227 Sommers Center', '19');
insert into Theatre (tname, address, zip) values ('Zaam-Dox', '0310 Reinke Junction', '14514');
insert into Theatre (tname, address, zip) values ('Greenlam', '56 Declaration Road', '04');
insert into Theatre (tname, address, zip) values ('Flowdesk', '49 Prentice Terrace', '60');
insert into Theatre (tname, address, zip) values ('Overhold', '4 Spenser Street', '42290');
insert into Theatre (tname, address, zip) values ('Zamit', '23 Nobel Drive', '3');
insert into Theatre (tname, address, zip) values ('Zaam-Dox', '840 Nobel Center', '3644');
insert into Theatre (tname, address, zip) values ('Solarbreeze', '32 Longview Hill', '39503');
insert into Theatre (tname, address, zip) values ('Voyatouch', '54 Green Ridge Center', '2153');
insert into Theatre (tname, address, zip) values ('Trippledex', '756 Brickson Park Junction', '94');
insert into Theatre (tname, address, zip) values ('Zaam-Dox', '81 Wayridge Crossing', '42818');
insert into Theatre (tname, address, zip) values ('Pannier', '16041 Gateway Crossing', '11');
insert into Theatre (tname, address, zip) values ('It', '82897 Fremont Park', '001');
insert into Theatre (tname, address, zip) values ('Gembucket', '532 Johnson Crossing', '21');
insert into Theatre (tname, address, zip) values ('Zamit', '0073 Johnson Point', '85');
insert into Theatre (tname, address, zip) values ('Andalax', '5 Shasta Hill', '81');
insert into Theatre (tname, address, zip) values ('Zontrax', '782 Prairie Rose Trail', '0384');
insert into Theatre (tname, address, zip) values ('Bitchip', '6 Sherman Circle', '1848');
insert into Theatre (tname, address, zip) values ('Sonsing', '95 Tomscot Lane', '8');
insert into Theatre (tname, address, zip) values ('Latlux', '15 Mitchell Junction', '5449');
insert into Theatre (tname, address, zip) values ('Bigtax', '4 Washington Avenue', '1922');
insert into Theatre (tname, address, zip) values ('Matsoft', '07 Carioca Trail', '312');
insert into Theatre (tname, address, zip) values ('Asoka', '84800 Garrison Drive', '63887');
insert into Theatre (tname, address, zip) values ('Biodex', '8 Sauthoff Crossing', '590');
insert into Theatre (tname, address, zip) values ('Mat Lam Tam', '24 Ronald Regan Parkway', '21');
insert into Theatre (tname, address, zip) values ('Holdlamis', '44 Oak Parkway', '67');
insert into Theatre (tname, address, zip) values ('Bigtax', '66 Scoville Lane', '1419');
insert into Theatre (tname, address, zip) values ('Daltfresh', '1906 Banding Point', '8');
insert into Theatre (tname, address, zip) values ('Prodder', '803 Scoville Court', '017');
insert into Theatre (tname, address, zip) values ('Lotstring', '4370 Glacier Hill Place', '1426');
insert into Theatre (tname, address, zip) values ('Bytecard', '3 Hovde Park', '652');
insert into Theatre (tname, address, zip) values ('Cookley', '6416 Killdeer Drive', '70268');
insert into Theatre (tname, address, zip) values ('Home Ing', '48018 Bowman Avenue', '98166');
insert into Theatre (tname, address, zip) values ('Lotstring', '4727 Grasskamp Place', '2188');
insert into Theatre (tname, address, zip) values ('Quo Lux', '32 Forest Center', '3');
insert into Theatre (tname, address, zip) values ('Temp', '853 Mosinee Plaza', '2');
insert into Theatre (tname, address, zip) values ('Ronstring', '40 Sage Trail', '344');
insert into Theatre (tname, address, zip) values ('Pannier', '3414 Northfield Alley', '7742');
insert into Theatre (tname, address, zip) values ('Zoolab', '13 Warner Plaza', '77940');
insert into Theatre (tname, address, zip) values ('Tempsoft', '837 School Way', '50');
insert into Theatre (tname, address, zip) values ('Ronstring', '55 Northwestern Pass', '97');
insert into Theatre (tname, address, zip) values ('Trippledex', '84932 Merry Way', '7434');
insert into Theatre (tname, address, zip) values ('Tresom', '9262 Schurz Park', '80');
insert into Theatre (tname, address, zip) values ('Bitchip', '42 Barby Terrace', '9');
insert into Theatre (tname, address, zip) values ('It', '65 Toban Street', '7597');
insert into Theatre (tname, address, zip) values ('Domainer', '206 Maryland Junction', '874');
insert into Theatre (tname, address, zip) values ('Hatity', '07514 Londonderry Alley', '87513');
insert into Theatre (tname, address, zip) values ('Ronstring', '2543 High Crossing Point', '15480');
insert into Theatre (tname, address, zip) values ('Viva', '4174 Bashford Street', '20554');
insert into Theatre (tname, address, zip) values ('Stringtough', '742 Green Drive', '1');
insert into Theatre (tname, address, zip) values ('Otcom', '40 Hansons Avenue', '2');
insert into Theatre (tname, address, zip) values ('Duobam', '98371 Upham Avenue', '5878');
insert into Theatre (tname, address, zip) values ('Span', '06994 Huxley Pass', '54');
insert into Theatre (tname, address, zip) values ('Konklux', '909 Blackbird Point', '21');
insert into Theatre (tname, address, zip) values ('Matsoft', '67259 Main Point', '936');
insert into Theatre (tname, address, zip) values ('Matsoft', '3 Sachtjen Court', '8');
insert into Theatre (tname, address, zip) values ('Alpha', '8 Gina Park', '4925');
insert into Theatre (tname, address, zip) values ('Zathin', '98562 Fairview Terrace', '588');
insert into Theatre (tname, address, zip) values ('Sonair', '269 Mockingbird Terrace', '60');
insert into Theatre (tname, address, zip) values ('Flowdesk', '39287 Sunbrook Alley', '081');
insert into Theatre (tname, address, zip) values ('Opela', '856 Scoville Trail', '0203');
insert into Theatre (tname, address, zip) values ('Alphazap', '13 Forest Dale Center', '9643');
insert into Theatre (tname, address, zip) values ('Kanlam', '28 Rockefeller Parkway', '7');
insert into Theatre (tname, address, zip) values ('Domainer', '9386 Carberry Park', '6467');
insert into Theatre (tname, address, zip) values ('Hatity', '7588 Russell Plaza', '69806');
insert into Theatre (tname, address, zip) values ('Home Ing', '62 Pleasure Park', '5121');
insert into Theatre (tname, address, zip) values ('Zathin', '85 Luster Circle', '6');
insert into Theatre (tname, address, zip) values ('Temp', '5 Sunbrook Crossing', '67363');
insert into Theatre (tname, address, zip) values ('Pannier', '75 Truax Circle', '59953');
insert into Theatre (tname, address, zip) values ('Aerified', '4663 Glacier Hill Drive', '853');
insert into Theatre (tname, address, zip) values ('Fintone', '4 Laurel Trail', '558');
insert into Theatre (tname, address, zip) values ('Ronstring', '9044 Sherman Alley', '8');
insert into Theatre (tname, address, zip) values ('Cookley', '6817 Hazelcrest Center', '0');
insert into Theatre (tname, address, zip) values ('Solarbreeze', '461 Hauk Center', '72263');
insert into Theatre (tname, address, zip) values ('Matsoft', '9152 Rieder Crossing', '22');
insert into Theatre (tname, address, zip) values ('Zamit', '9 Susan Junction', '46');
insert into Theatre (tname, address, zip) values ('Vagram', '28653 Northridge Street', '8936');
insert into Theatre (tname, address, zip) values ('Sub-Ex', '547 Victoria Park', '5357');
insert into Theatre (tname, address, zip) values ('Bamity', '6 Eagan Junction', '7');
insert into Theatre (tname, address, zip) values ('Cardify', '090 Oneill Avenue', '4');
insert into Theatre (tname, address, zip) values ('Cardguard', '475 Florence Street', '18');
insert into Theatre (tname, address, zip) values ('Otcom', '35587 Burrows Parkway', '109');
insert into Theatre (tname, address, zip) values ('Andalax', '527 Stephen Trail', '1020');
insert into Theatre (tname, address, zip) values ('Solarbreeze', '0365 Waubesa Alley', '2292');
insert into Theatre (tname, address, zip) values ('Konklux', '25 Namekagon Parkway', '20');
insert into Theatre (tname, address, zip) values ('Regrant', '101 Harbort Center', '79');
insert into Theatre (tname, address, zip) values ('Treeflex', '629 Meadow Valley Terrace', '7');
insert into Theatre (tname, address, zip) values ('Alpha', '796 Farragut Way', '183');
insert into Theatre (tname, address, zip) values ('Prodder', '31576 Killdeer Place', '0811');
insert into Theatre (tname, address, zip) values ('Pannier', '2 Dunning Pass', '59');
insert into Theatre (tname, address, zip) values ('Voyatouch', '05630 Jenna Pass', '4');
insert into Theatre (tname, address, zip) values ('Konklab', '36 Lotheville Avenue', '03596');
insert into Theatre (tname, address, zip) values ('Vagram', '200 Burrows Place', '11');
insert into Theatre (tname, address, zip) values ('Holdlamis', '44962 Macpherson Avenue', '94710');
insert into Theatre (tname, address, zip) values ('Zoolab', '02 Trailsway Pass', '6191');
insert into Theatre (tname, address, zip) values ('Fix San', '65526 La Follette Way', '98');
insert into Theatre (tname, address, zip) values ('Alphazap', '5742 Grover Plaza', '90479');
insert into Theatre (tname, address, zip) values ('Span', '724 Katie Point', '6021');
insert into Theatre (tname, address, zip) values ('Overhold', '25534 Esch Alley', '17354');
insert into Theatre (tname, address, zip) values ('Domainer', '9 Loeprich Lane', '8');
insert into Theatre (tname, address, zip) values ('Voltsillam', '2094 South Way', '0');
insert into Theatre (tname, address, zip) values ('Tres-Zap', '0 Clarendon Park', '50');
insert into Theatre (tname, address, zip) values ('Gembucket', '09115 Del Mar Street', '13');
insert into Theatre (tname, address, zip) values ('Lotlux', '42109 Glendale Drive', '933');
insert into Theatre (tname, address, zip) values ('Biodex', '2 Shoshone Park', '8594');
insert into Theatre (tname, address, zip) values ('Treeflex', '19 Harper Circle', '3810');
insert into Theatre (tname, address, zip) values ('Treeflex', '70852 Ohio Street', '53252');
insert into Theatre (tname, address, zip) values ('Overhold', '14 Luster Parkway', '4453');
insert into Theatre (tname, address, zip) values ('Voyatouch', '7 Little Fleur Parkway', '4');
insert into Theatre (tname, address, zip) values ('Lotstring', '079 Westerfield Plaza', '6073');
insert into Theatre (tname, address, zip) values ('Lotstring', '20550 Anhalt Place', '50448');
insert into Theatre (tname, address, zip) values ('Asoka', '6 Mockingbird Place', '627');
insert into Theatre (tname, address, zip) values ('Alphazap', '881 Messerschmidt Trail', '7713');
insert into Theatre (tname, address, zip) values ('Zoolab', '595 Farwell Road', '7298');
insert into Theatre (tname, address, zip) values ('Hatity', '5 Burning Wood Hill', '337');
insert into Theatre (tname, address, zip) values ('Sonair', '5 Continental Crossing', '2270');
insert into Theatre (tname, address, zip) values ('Stim', '1837 Sullivan Trail', '664');
insert into Theatre (tname, address, zip) values ('Namfix', '23 Lakeland Park', '81');
insert into Theatre (tname, address, zip) values ('Asoka', '48248 Schlimgen Parkway', '52814');
insert into Theatre (tname, address, zip) values ('Cookley', '96 Grasskamp Trail', '3593');
insert into Theatre (tname, address, zip) values ('Cardify', '6178 Ridgeview Plaza', '1459');
insert into Theatre (tname, address, zip) values ('Mat Lam Tam', '688 Morningstar Place', '968');
insert into Theatre (tname, address, zip) values ('Zaam-Dox', '21543 Mendota Junction', '77');
insert into Theatre (tname, address, zip) values ('Y-Solowarm', '90521 Erie Center', '00');
insert into Theatre (tname, address, zip) values ('Latlux', '23215 Lotheville Drive', '06139');
insert into Theatre (tname, address, zip) values ('Konklab', '4 Lukken Drive', '550');
insert into Theatre (tname, address, zip) values ('Holdlamis', '3 Miller Way', '31');
insert into Theatre (tname, address, zip) values ('Rank', '27132 Crest Line Park', '1750');
insert into Theatre (tname, address, zip) values ('Veribet', '3 Algoma Pass', '3');
insert into Theatre (tname, address, zip) values ('Opela', '83 Maywood Terrace', '801');
insert into Theatre (tname, address, zip) values ('Duobam', '2 Monica Hill', '2639');
insert into Theatre (tname, address, zip) values ('Cardify', '33 Talisman Center', '873');
insert into Theatre (tname, address, zip) values ('Prodder', '39 Browning Trail', '1631');
insert into Theatre (tname, address, zip) values ('Konklux', '0 Forest Run Alley', '4632');
insert into Theatre (tname, address, zip) values ('Lotstring', '21 Thierer Crossing', '30128');
insert into Theatre (tname, address, zip) values ('Flowdesk', '84289 Northridge Pass', '75330');
insert into Theatre (tname, address, zip) values ('Tin', '39 8th Pass', '335');
insert into Theatre (tname, address, zip) values ('Temp', '5164 Independence Alley', '1730');
insert into Theatre (tname, address, zip) values ('Home Ing', '08492 Rockefeller Terrace', '0');
insert into Theatre (tname, address, zip) values ('Regrant', '6028 Granby Hill', '48452');
insert into Theatre (tname, address, zip) values ('Job', '1 Nevada Park', '69994');
insert into Theatre (tname, address, zip) values ('Bigtax', '0059 Springs Circle', '90985');
insert into Theatre (tname, address, zip) values ('Sub-Ex', '14416 Kingsford Place', '47443');
insert into Theatre (tname, address, zip) values ('Tampflex', '6 Kennedy Plaza', '3201');
insert into Theatre (tname, address, zip) values ('Cardify', '433 Londonderry Way', '5');
insert into Theatre (tname, address, zip) values ('Tres-Zap', '88 Merchant Road', '0291');
insert into Theatre (tname, address, zip) values ('Kanlam', '29 Sutteridge Alley', '600');
insert into Theatre (tname, address, zip) values ('Zoolab', '31 Kedzie Pass', '4');
insert into Theatre (tname, address, zip) values ('Keylex', '75493 Blackbird Hill', '232');
insert into Theatre (tname, address, zip) values ('Sonair', '47 Emmet Plaza', '923');
insert into Theatre (tname, address, zip) values ('Bigtax', '8 Mitchell Pass', '67279');
insert into Theatre (tname, address, zip) values ('Greenlam', '38147 Becker Lane', '53');
insert into Theatre (tname, address, zip) values ('Flowdesk', '9 Duke Pass', '87901');
insert into Theatre (tname, address, zip) values ('Matsoft', '24 Sunfield Crossing', '7150');
insert into Theatre (tname, address, zip) values ('Opela', '0 Garrison Junction', '03');
insert into Theatre (tname, address, zip) values ('Fix San', '8 Bunting Way', '44');
insert into Theatre (tname, address, zip) values ('Gembucket', '15 Morrow Pass', '293');
insert into Theatre (tname, address, zip) values ('Pannier', '1284 Buell Plaza', '08824');
insert into Theatre (tname, address, zip) values ('Zamit', '36592 Mccormick Circle', '4951');
insert into Theatre (tname, address, zip) values ('Bamity', '7902 John Wall Terrace', '9479');
insert into Theatre (tname, address, zip) values ('Lotstring', '7 Autumn Leaf Point', '7');
insert into Theatre (tname, address, zip) values ('Sonair', '871 Basil Plaza', '064');
insert into Theatre (tname, address, zip) values ('Stringtough', '195 Veith Pass', '84780');
insert into Theatre (tname, address, zip) values ('Stronghold', '50 Sullivan Point', '9660');
insert into Theatre (tname, address, zip) values ('Alphazap', '284 Armistice Plaza', '10728');
insert into Theatre (tname, address, zip) values ('Stim', '357 Onsgard Trail', '91990');
insert into Theatre (tname, address, zip) values ('Bitchip', '0 Kipling Alley', '298');
insert into Theatre (tname, address, zip) values ('Sub-Ex', '056 Trailsway Trail', '25');
insert into Theatre (tname, address, zip) values ('Zamit', '884 Ryan Place', '675');
insert into Theatre (tname, address, zip) values ('Bamity', '27459 Glacier Hill Road', '0374');
insert into Theatre (tname, address, zip) values ('Alpha', '48 Barby Plaza', '51');
insert into Theatre (tname, address, zip) values ('Viva', '5666 Hazelcrest Street', '61329');
insert into Theatre (tname, address, zip) values ('Fix San', '1772 Homewood Hill', '219');
insert into Theatre (tname, address, zip) values ('Temp', '8 Golden Leaf Avenue', '34854');
insert into Theatre (tname, address, zip) values ('Overhold', '35770 John Wall Drive', '02');
insert into Theatre (tname, address, zip) values ('Rank', '13 Upham Junction', '881');
insert into Theatre (tname, address, zip) values ('Overhold', '3 Artisan Pass', '403');
insert into Theatre (tname, address, zip) values ('Toughjoyfax', '8017 Rieder Parkway', '62957');
insert into Theatre (tname, address, zip) values ('Matsoft', '94585 Maple Wood Parkway', '7');
insert into Theatre (tname, address, zip) values ('Stim', '122 Portage Center', '3');
insert into Theatre (tname, address, zip) values ('Transcof', '4 Heffernan Alley', '82');
insert into Theatre (tname, address, zip) values ('Bigtax', '963 Jenna Court', '8');
insert into Theatre (tname, address, zip) values ('Otcom', '04160 Riverside Crossing', '8');
insert into Theatre (tname, address, zip) values ('Andalax', '08162 Stephen Parkway', '3');
insert into Theatre (tname, address, zip) values ('Voyatouch', '64 Ludington Trail', '90494');
insert into Theatre (tname, address, zip) values ('Fix San', '4963 Maple Drive', '7');
insert into Theatre (tname, address, zip) values ('Subin', '68269 Swallow Point', '41');
insert into Theatre (tname, address, zip) values ('Otcom', '097 Nobel Road', '27274');
insert into Theatre (tname, address, zip) values ('Sub-Ex', '1 Bartelt Street', '671');
insert into Theatre (tname, address, zip) values ('Bigtax', '408 Oak Valley Pass', '45');
insert into Theatre (tname, address, zip) values ('Zontrax', '55945 Havey Point', '7');
insert into Theatre (tname, address, zip) values ('Toughjoyfax', '8 Gina Park', '41477');
insert into Theatre (tname, address, zip) values ('Sonair', '7 Marquette Way', '2317');
insert into Theatre (tname, address, zip) values ('Aerified', '63175 Stuart Street', '491');
insert into Theatre (tname, address, zip) values ('Zontrax', '358 Trailsway Plaza', '69318');
insert into Theatre (tname, address, zip) values ('Gembucket', '03 Beilfuss Road', '42611');
insert into Theatre (tname, address, zip) values ('Cookley', '1630 Dwight Drive', '8');
insert into Theatre (tname, address, zip) values ('Voltsillam', '6 Merchant Terrace', '283');
insert into Theatre (tname, address, zip) values ('Solarbreeze', '3773 Blackbird Way', '9');
insert into Theatre (tname, address, zip) values ('Transcof', '50 Milwaukee Trail', '153');
insert into Theatre (tname, address, zip) values ('Job', '1541 Mosinee Trail', '30934');
insert into Theatre (tname, address, zip) values ('Tres-Zap', '608 Sommers Terrace', '2');
insert into Theatre (tname, address, zip) values ('Tres-Zap', '13117 Utah Avenue', '6');
insert into Theatre (tname, address, zip) values ('Treeflex', '56 Texas Circle', '24701');
insert into Theatre (tname, address, zip) values ('Asoka', '04200 Walton Terrace', '38171');
insert into Theatre (tname, address, zip) values ('Namfix', '558 Springs Trail', '7');
insert into Theatre (tname, address, zip) values ('Alpha', '0 Emmet Court', '98019');
insert into Theatre (tname, address, zip) values ('Duobam', '64 Stone Corner Way', '1370');
insert into Theatre (tname, address, zip) values ('Fintone', '33 Crescent Oaks Crossing', '861');
insert into Theatre (tname, address, zip) values ('Rank', '276 Mayer Way', '9');
insert into Theatre (tname, address, zip) values ('Tresom', '23779 Golden Leaf Terrace', '4752');
insert into Theatre (tname, address, zip) values ('Rank', '0620 Center Hill', '33');
insert into Theatre (tname, address, zip) values ('Alpha', '68549 Northfield Place', '00');
insert into Theatre (tname, address, zip) values ('Otcom', '8 Artisan Terrace', '8097');
insert into Theatre (tname, address, zip) values ('Latlux', '41414 Scofield Avenue', '6');
insert into Theatre (tname, address, zip) values ('Redhold', '7506 Grasskamp Road', '37');
insert into Theatre (tname, address, zip) values ('Zoolab', '0 Burning Wood Plaza', '0889');
insert into Theatre (tname, address, zip) values ('Matsoft', '21834 Dovetail Pass', '267');
insert into Theatre (tname, address, zip) values ('Zathin', '4 Tennessee Point', '5145');
insert into Theatre (tname, address, zip) values ('Lotstring', '235 Meadow Valley Road', '19656');
insert into Theatre (tname, address, zip) values ('Sonair', '3782 Miller Terrace', '2');
insert into Theatre (tname, address, zip) values ('Mat Lam Tam', '93340 Marquette Road', '3');
insert into Theatre (tname, address, zip) values ('Home Ing', '5886 Susan Pass', '483');
insert into Theatre (tname, address, zip) values ('Trippledex', '63 Mcguire Trail', '1310');
insert into Theatre (tname, address, zip) values ('Fix San', '603 Mendota Plaza', '4024');
insert into Theatre (tname, address, zip) values ('Flowdesk', '71524 Welch Hill', '7');
insert into Theatre (tname, address, zip) values ('Konklux', '273 Everett Park', '10478');
insert into Theatre (tname, address, zip) values ('Aerified', '54 4th Avenue', '09');
insert into Theatre (tname, address, zip) values ('Tresom', '654 Oak Court', '10');
insert into Theatre (tname, address, zip) values ('It', '930 Lien Lane', '1');
insert into Theatre (tname, address, zip) values ('Andalax', '3792 Bunker Hill Place', '34');
insert into Theatre (tname, address, zip) values ('Tampflex', '35618 Melvin Parkway', '56');
insert into Theatre (tname, address, zip) values ('Opela', '711 Sherman Center', '5');
insert into Theatre (tname, address, zip) values ('Viva', '73 Esch Trail', '88489');
insert into Theatre (tname, address, zip) values ('Transcof', '0 Hazelcrest Point', '75783');
insert into Theatre (tname, address, zip) values ('Alphazap', '39679 Sullivan Way', '59');
insert into Theatre (tname, address, zip) values ('Rank', '76 Acker Street', '323');
insert into Theatre (tname, address, zip) values ('It', '86245 Graceland Lane', '3');
insert into Theatre (tname, address, zip) values ('Trippledex', '7676 Declaration Avenue', '6573');
insert into Theatre (tname, address, zip) values ('Aerified', '30 Hanson Avenue', '7995');
insert into Theatre (tname, address, zip) values ('Andalax', '1322 Texas Avenue', '3');
insert into Theatre (tname, address, zip) values ('Bigtax', '78 Butterfield Circle', '594');
insert into Theatre (tname, address, zip) values ('Domainer', '117 Maryland Trail', '274');
insert into Theatre (tname, address, zip) values ('Temp', '16651 Sheridan Crossing', '1');
insert into Theatre (tname, address, zip) values ('Mat Lam Tam', '78 Green Hill', '36');
insert into Theatre (tname, address, zip) values ('Hatity', '07 Marcy Parkway', '00');
insert into Theatre (tname, address, zip) values ('Transcof', '56426 Golf Course Lane', '9340');
insert into Theatre (tname, address, zip) values ('Greenlam', '8137 Delladonna Crossing', '6');
insert into Theatre (tname, address, zip) values ('Matsoft', '8043 Knutson Avenue', '4');
insert into Theatre (tname, address, zip) values ('Home Ing', '8041 Bartelt Alley', '19');
insert into Theatre (tname, address, zip) values ('Regrant', '3550 Fisk Avenue', '615');
insert into Theatre (tname, address, zip) values ('Regrant', '98591 Dawn Street', '178');
insert into Theatre (tname, address, zip) values ('Rank', '490 Center Trail', '8');
insert into Theatre (tname, address, zip) values ('Matsoft', '5 Bayside Road', '58016');
insert into Theatre (tname, address, zip) values ('Flexidy', '2628 Columbus Center', '800');
insert into Theatre (tname, address, zip) values ('Aerified', '355 Sauthoff Lane', '985');
insert into Theatre (tname, address, zip) values ('Cardify', '63 New Castle Alley', '55');
insert into Theatre (tname, address, zip) values ('Wrapsafe', '9622 Summerview Crossing', '79');
insert into Theatre (tname, address, zip) values ('Matsoft', '8027 Ridge Oak Terrace', '44');
insert into Theatre (tname, address, zip) values ('Regrant', '90221 Main Way', '60');
insert into Theatre (tname, address, zip) values ('Bitchip', '62 7th Hill', '343');
insert into Theatre (tname, address, zip) values ('Tin', '392 Main Plaza', '0');
insert into Theatre (tname, address, zip) values ('Y-find', '2 Debs Point', '5');
insert into Theatre (tname, address, zip) values ('Cardify', '213 Union Place', '68');
insert into Theatre (tname, address, zip) values ('Trippledex', '6207 Farragut Alley', '9411');
insert into Theatre (tname, address, zip) values ('Treeflex', '14 Artisan Lane', '0544');
insert into Theatre (tname, address, zip) values ('Stringtough', '4 Bellgrove Drive', '81');
insert into Theatre (tname, address, zip) values ('Bitchip', '735 Kensington Parkway', '07769');
insert into Theatre (tname, address, zip) values ('Vagram', '6509 Westridge Junction', '7344');
insert into Theatre (tname, address, zip) values ('Wrapsafe', '990 Twin Pines Trail', '9');
insert into Theatre (tname, address, zip) values ('Stronghold', '67 Lotheville Parkway', '8');
insert into Theatre (tname, address, zip) values ('Ronstring', '0 Park Meadow Point', '80345');
insert into Theatre (tname, address, zip) values ('Duobam', '089 Pierstorff Hill', '0285');
insert into Theatre (tname, address, zip) values ('Namfix', '8 Truax Lane', '87');
insert into Theatre (tname, address, zip) values ('Mat Lam Tam', '48500 Westport Avenue', '5');
insert into Theatre (tname, address, zip) values ('Sonair', '644 Hermina Plaza', '42287');
insert into Theatre (tname, address, zip) values ('Viva', '8 Farwell Court', '8');
insert into Theatre (tname, address, zip) values ('Alphazap', '161 Fuller Pass', '7145');
insert into Theatre (tname, address, zip) values ('Ronstring', '9 Waywood Street', '7348');
insert into Theatre (tname, address, zip) values ('Flowdesk', '868 Di Loreto Road', '76791');
insert into Theatre (tname, address, zip) values ('Vagram', '2 Lakeland Way', '0');
insert into Theatre (tname, address, zip) values ('Subin', '48647 Clemons Avenue', '4');
insert into Theatre (tname, address, zip) values ('Zontrax', '1 Nelson Trail', '23287');
insert into Theatre (tname, address, zip) values ('Ronstring', '0831 Warner Crossing', '0');
insert into Theatre (tname, address, zip) values ('Holdlamis', '3656 Artisan Terrace', '21');
insert into Theatre (tname, address, zip) values ('Toughjoyfax', '3 Walton Crossing', '55101');
insert into Theatre (tname, address, zip) values ('Asoka', '0245 5th Terrace', '31');
insert into Theatre (tname, address, zip) values ('Stringtough', '7545 Vahlen Avenue', '7');
insert into Theatre (tname, address, zip) values ('Keylex', '09 Anniversary Trail', '3');
insert into Theatre (tname, address, zip) values ('Redhold', '691 Killdeer Center', '5504');
insert into Theatre (tname, address, zip) values ('Cardify', '5838 Stuart Trail', '9');
insert into Theatre (tname, address, zip) values ('Span', '9 Center Plaza', '86778');
insert into Theatre (tname, address, zip) values ('Bamity', '635 Crest Line Way', '52');
insert into Theatre (tname, address, zip) values ('Ventosanzap', '693 Cambridge Avenue', '753');
insert into Theatre (tname, address, zip) values ('Quo Lux', '1 Crowley Hill', '345');
insert into Theatre (tname, address, zip) values ('Bitchip', '2 Swallow Pass', '22382');
insert into Theatre (tname, address, zip) values ('Hatity', '50 Colorado Crossing', '64');
insert into Theatre (tname, address, zip) values ('Bytecard', '85 Stang Circle', '3981');
insert into Theatre (tname, address, zip) values ('Wrapsafe', '1 Northridge Circle', '757');
insert into Theatre (tname, address, zip) values ('Stim', '5 Hoffman Junction', '93');
insert into Theatre (tname, address, zip) values ('Rank', '9 Ridgeview Parkway', '7724');
insert into Theatre (tname, address, zip) values ('Job', '11694 Stang Alley', '1');
insert into Theatre (tname, address, zip) values ('Solarbreeze', '216 Crownhardt Court', '209');
insert into Theatre (tname, address, zip) values ('Zaam-Dox', '66524 Fairview Drive', '42701');
insert into Theatre (tname, address, zip) values ('It', '700 Sutteridge Parkway', '855');
insert into Theatre (tname, address, zip) values ('Biodex', '7983 Elka Terrace', '5');
insert into Theatre (tname, address, zip) values ('Stringtough', '2 Lerdahl Center', '0488');
insert into Theatre (tname, address, zip) values ('Rank', '780 Debra Trail', '5100');
insert into Theatre (tname, address, zip) values ('Span', '4831 Commercial Alley', '927');
insert into Theatre (tname, address, zip) values ('Domainer', '615 Fordem Point', '07708');
insert into Theatre (tname, address, zip) values ('Otcom', '299 Gateway Avenue', '838');
insert into Theatre (tname, address, zip) values ('Kanlam', '206 Coolidge Terrace', '96');
insert into Theatre (tname, address, zip) values ('Cardguard', '31 Fairfield Trail', '19');
insert into Theatre (tname, address, zip) values ('Daltfresh', '5 Jenifer Point', '597');
insert into Theatre (tname, address, zip) values ('Transcof', '2 Lien Lane', '6916');
insert into Theatre (tname, address, zip) values ('Sonair', '9344 Lerdahl Crossing', '170');
insert into Theatre (tname, address, zip) values ('Bytecard', '11 Hooker Drive', '016');
insert into Theatre (tname, address, zip) values ('Fintone', '8 Steensland Lane', '499');
insert into Theatre (tname, address, zip) values ('Keylex', '92652 Daystar Street', '26462');
insert into Theatre (tname, address, zip) values ('Quo Lux', '07 Kenwood Court', '988');
insert into Theatre (tname, address, zip) values ('Solarbreeze', '5 Jenna Junction', '493');
insert into Theatre (tname, address, zip) values ('Voltsillam', '831 Montana Road', '2458');
insert into Theatre (tname, address, zip) values ('Cookley', '40 Heath Terrace', '7412');
insert into Theatre (tname, address, zip) values ('Rank', '7 Merrick Street', '872');
insert into Theatre (tname, address, zip) values ('Biodex', '9386 Coleman Trail', '81');
insert into Theatre (tname, address, zip) values ('Sub-Ex', '36688 Northland Avenue', '47261');
insert into Theatre (tname, address, zip) values ('Ventosanzap', '5370 Dunning Point', '76665');
insert into Theatre (tname, address, zip) values ('Konklab', '20549 Manufacturers Place', '36');
insert into Theatre (tname, address, zip) values ('Alpha', '60 Larry Street', '0');
insert into Theatre (tname, address, zip) values ('Stringtough', '780 Texas Crossing', '717');
insert into Theatre (tname, address, zip) values ('Stringtough', '93 Forest Run Street', '817');
insert into Theatre (tname, address, zip) values ('Bamity', '725 Bluestem Lane', '39');
insert into Theatre (tname, address, zip) values ('Zoolab', '573 Donald Place', '5351');
insert into Theatre (tname, address, zip) values ('Span', '70848 Randy Point', '3');
insert into Theatre (tname, address, zip) values ('Subin', '635 Butternut Parkway', '4');
insert into Theatre (tname, address, zip) values ('Tin', '934 Lotheville Hill', '90');
insert into Theatre (tname, address, zip) values ('Stim', '02795 Graceland Alley', '16800');
insert into Theatre (tname, address, zip) values ('Transcof', '8 Havey Hill', '4390');
insert into Theatre (tname, address, zip) values ('Keylex', '20842 Dunning Road', '773');
insert into Theatre (tname, address, zip) values ('Biodex', '823 Darwin Alley', '1165');
insert into Theatre (tname, address, zip) values ('Konklux', '677 Harbort Alley', '10');
insert into Theatre (tname, address, zip) values ('Cardguard', '7884 Cordelia Park', '501');
insert into Theatre (tname, address, zip) values ('Sonair', '33 Graedel Park', '3');
insert into Theatre (tname, address, zip) values ('Zaam-Dox', '5131 Hallows Crossing', '8252');
insert into Theatre (tname, address, zip) values ('Solarbreeze', '32065 Buhler Street', '7454');
insert into Theatre (tname, address, zip) values ('Stim', '6 Forest Run Alley', '7');
insert into Theatre (tname, address, zip) values ('Hatity', '88337 Darwin Parkway', '5');
insert into Theatre (tname, address, zip) values ('Home Ing', '80389 Northport Junction', '89285');
insert into Theatre (tname, address, zip) values ('Subin', '21555 Randy Crossing', '8');
insert into Theatre (tname, address, zip) values ('Home Ing', '66 Aberg Trail', '77173');
insert into Theatre (tname, address, zip) values ('Sub-Ex', '97581 Jenna Crossing', '18916');
insert into Theatre (tname, address, zip) values ('Lotstring', '8 Ludington Way', '87519');
insert into Theatre (tname, address, zip) values ('Zaam-Dox', '10392 Prairie Rose Road', '9');
insert into Theatre (tname, address, zip) values ('Sub-Ex', '73 Oriole Alley', '31437');
insert into Theatre (tname, address, zip) values ('Pannier', '16891 Kingsford Avenue', '89');
insert into Theatre (tname, address, zip) values ('Wrapsafe', '77756 Cordelia Place', '822');
insert into Theatre (tname, address, zip) values ('Voyatouch', '1 Grayhawk Park', '01067');
insert into Theatre (tname, address, zip) values ('Stringtough', '737 Marquette Circle', '93813');
insert into Theatre (tname, address, zip) values ('Alpha', '07 Longview Plaza', '3');
insert into Theatre (tname, address, zip) values ('Stringtough', '9224 Transport Pass', '427');
insert into Theatre (tname, address, zip) values ('Trippledex', '7 Becker Lane', '1149');
insert into Theatre (tname, address, zip) values ('Transcof', '83 Milwaukee Lane', '97098');
insert into Theatre (tname, address, zip) values ('Y-Solowarm', '1066 Nova Plaza', '6149');
insert into Theatre (tname, address, zip) values ('Zontrax', '856 Oneill Park', '0');
insert into Theatre (tname, address, zip) values ('Fintone', '46616 Mesta Hill', '48');
insert into Theatre (tname, address, zip) values ('Redhold', '46 Havey Point', '59');
insert into Theatre (tname, address, zip) values ('Ronstring', '61 Armistice Terrace', '0671');
insert into Theatre (tname, address, zip) values ('Cardify', '47 Service Drive', '7497');
insert into Theatre (tname, address, zip) values ('Fix San', '438 Merchant Junction', '9');
insert into Theatre (tname, address, zip) values ('It', '60285 Valley Edge Pass', '56298');
insert into Theatre (tname, address, zip) values ('Stronghold', '6 Moland Junction', '5');
insert into Theatre (tname, address, zip) values ('Tempsoft', '08040 Bay Point', '9');
insert into Theatre (tname, address, zip) values ('Tampflex', '80 Meadow Vale Lane', '314');
insert into Theatre (tname, address, zip) values ('Redhold', '697 Sugar Parkway', '85653');
insert into Theatre (tname, address, zip) values ('Tampflex', '912 Grim Drive', '15');
insert into Theatre (tname, address, zip) values ('Flexidy', '45 Maple Wood Road', '3310');
insert into Theatre (tname, address, zip) values ('Sonsing', '5 Doe Crossing Point', '38502');
insert into Theatre (tname, address, zip) values ('Tampflex', '21 1st Junction', '2');
insert into Theatre (tname, address, zip) values ('Bitwolf', '80691 South Drive', '61760');
insert into Theatre (tname, address, zip) values ('Rank', '1746 Mandrake Place', '129');
insert into Theatre (tname, address, zip) values ('Lotstring', '030 Rieder Park', '766');
insert into Theatre (tname, address, zip) values ('Opela', '5 Roxbury Way', '103');
insert into Theatre (tname, address, zip) values ('Cookley', '24071 Morning Terrace', '2');
insert into Theatre (tname, address, zip) values ('Duobam', '44 Waubesa Road', '4275');
insert into Theatre (tname, address, zip) values ('Rank', '8 Daystar Drive', '43');
insert into Theatre (tname, address, zip) values ('Wrapsafe', '894 Ohio Park', '509');
insert into Theatre (tname, address, zip) values ('Domainer', '35850 Parkside Point', '601');
insert into Theatre (tname, address, zip) values ('Vagram', '0 International Way', '870');
insert into Theatre (tname, address, zip) values ('Lotlux', '3628 Northland Pass', '1662');
insert into Theatre (tname, address, zip) values ('Latlux', '7143 Service Plaza', '96562');
insert into Theatre (tname, address, zip) values ('Voyatouch', '3432 Welch Drive', '73891');
insert into Theatre (tname, address, zip) values ('Lotlux', '7505 Porter Point', '5299');
insert into Theatre (tname, address, zip) values ('Tempsoft', '71867 Luster Center', '5');
insert into Theatre (tname, address, zip) values ('Flexidy', '13447 Fordem Plaza', '5807');
insert into Theatre (tname, address, zip) values ('Treeflex', '521 Graedel Alley', '91');
insert into Theatre (tname, address, zip) values ('Alpha', '0928 Eggendart Plaza', '09');
insert into Theatre (tname, address, zip) values ('Tres-Zap', '8775 Iowa Hill', '31');
insert into Theatre (tname, address, zip) values ('Fintone', '72 Melrose Crossing', '96');
insert into Theatre (tname, address, zip) values ('Kanlam', '529 Sloan Avenue', '1');
insert into Theatre (tname, address, zip) values ('Solarbreeze', '16 Delladonna Place', '00');
insert into Theatre (tname, address, zip) values ('Bamity', '64640 Arizona Lane', '80306');
insert into Theatre (tname, address, zip) values ('Voyatouch', '051 Katie Lane', '9273');
insert into Theatre (tname, address, zip) values ('Job', '3963 Haas Street', '5');
insert into Theatre (tname, address, zip) values ('Flowdesk', '9 Stephen Junction', '2866');
insert into Theatre (tname, address, zip) values ('Mat Lam Tam', '3 Reindahl Way', '35509');
insert into Theatre (tname, address, zip) values ('Fix San', '5 Caliangt Center', '4');
insert into Theatre (tname, address, zip) values ('Lotstring', '66 Crest Line Court', '60');
insert into Theatre (tname, address, zip) values ('Sub-Ex', '3147 Forest Dale Lane', '458');
insert into Theatre (tname, address, zip) values ('Keylex', '8452 Melvin Terrace', '290');
insert into Theatre (tname, address, zip) values ('Domainer', '20 Stoughton Trail', '84949');
insert into Theatre (tname, address, zip) values ('Tresom', '912 Arkansas Court', '94');
insert into Theatre (tname, address, zip) values ('Bytecard', '703 Lakewood Alley', '320');
insert into Theatre (tname, address, zip) values ('Redhold', '78429 Hooker Place', '7');
insert into Theatre (tname, address, zip) values ('Domainer', '93976 Dapin Court', '093');
insert into Theatre (tname, address, zip) values ('Lotlux', '161 Carioca Point', '2323');
insert into Theatre (tname, address, zip) values ('Lotstring', '77660 Dixon Park', '4136');
insert into Theatre (tname, address, zip) values ('Stronghold', '71 Luster Terrace', '0');
insert into Theatre (tname, address, zip) values ('Konklux', '1 Talisman Junction', '2167');
insert into Theatre (tname, address, zip) values ('Matsoft', '8886 Commercial Park', '782');
insert into Theatre (tname, address, zip) values ('Treeflex', '96046 Nancy Park', '4618');
insert into Theatre (tname, address, zip) values ('Fintone', '531 Autumn Leaf Plaza', '0');
insert into Theatre (tname, address, zip) values ('Alphazap', '4 Thackeray Junction', '7');
insert into Theatre (tname, address, zip) values ('Bitwolf', '338 Tony Point', '803');
insert into Theatre (tname, address, zip) values ('Greenlam', '79 Bowman Pass', '4376');
insert into Theatre (tname, address, zip) values ('Lotstring', '2705 Melvin Pass', '08621');
insert into Theatre (tname, address, zip) values ('Sub-Ex', '6 Forster Street', '1');
insert into Theatre (tname, address, zip) values ('Keylex', '4 Pearson Way', '2');
insert into Theatre (tname, address, zip) values ('Temp', '4961 Fairview Parkway', '4871');
insert into Theatre (tname, address, zip) values ('Stronghold', '526 American Ash Terrace', '667');
insert into Theatre (tname, address, zip) values ('Opela', '81 Homewood Lane', '9732');
insert into Theatre (tname, address, zip) values ('Stringtough', '4 Sherman Plaza', '812');
insert into Theatre (tname, address, zip) values ('Bigtax', '56 6th Pass', '8');
